server:
  port: 8081
spring:
  datasource:
    username: root
    password: Bhaskar@71
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quizdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: quiz-service

